### Typical get all
GET http://localhost:3003/api/blogs

### Typical add new blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json;charset=UTF-8

{
  "title": "from VS Code REST4",
  "author": "vsc4",
  "url": "https://facebook4.com",
  "likes": 4
}

### Add new blog post without likes
POST http://localhost:3003/api/blogs
Content-Type: application/json;charset=UTF-8

{
  "title": "missing likes!",
  "author": "no likes!",
  "url": "https://no-like.com"
}
