### Typical get all
GET http://localhost:3003/api/blogs

### Typical add new blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json;charset=UTF-8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjI5MjllZjZkYzZjMjYzMDVkNWRkZjNjIiwiaWF0IjoxNjUzNzc2MTI1fQ.ruiMxsgOrwK6Hvp1IqCywIhf5eKt2bFL3R_C81dNVCc

{
  "title": "a new take on ruby on rails",
  "author": "hellas",
  "url": "https://RuboRails.io",
  "likes": 2
}

### Add new blog post without likes -- needs valid token
# POST http://localhost:3003/api/blogs
# Content-Type: application/json;charset=UTF-8

# {
#   "title": "missing likes!",
#   "author": "no likes!",
#   "url": "https://no-like.com"
# }

### DELETE a blog post
DELETE http://localhost:3003/api/blogs/62930dd9bcb7a3d23fa4bb03
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjI5MjllZjZkYzZjMjYzMDVkNWRkZjNjIiwiaWF0IjoxNjUzNzc2MTI1fQ.ruiMxsgOrwK6Hvp1IqCywIhf5eKt2bFL3R_C81dNVCc

### DELETE a blog post -- incorrect credentials (correct id, valid token, but author id token is not matching with blog user id)
DELETE http://localhost:3003/api/blogs/62930dd9bcb7a3d23fa4bb03
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjI5MjllZjZkYzZjMjYzMDVkNWRkZjNjIiwiaWF0IjoxNjUzNzc2MTI1fQ.ruiMxsgOrwK6Hvp1IqCywIhf5eKt2bFL3R_C81dNVCc

### DELETE a blog post -- incorrect token
DELETE http://localhost:3003/api/blogs/62925a7ac84829172d4be731
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjI5MjllZjZkYzZjMjYzMDVkNWRkZjNjIiwiaWF0IjoxNjUzNzc2MTI1fQ.ruiMxsgOrwK6Hvp1IqCywIhf5eKt2bFL3R_CAAANVCc