### Typical get all
GET http://localhost:3003/api/blogs

### Typical add new blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json;charset=UTF-8

{
  "title": "from VS Code REST3",
  "author": "vsc3",
  "url": "https://facebook3.com",
  "likes": 5
}

### Delete 